const frase = [
'Eu sou luz',
' Eu sou amor',
'Eu sou cura', 
'Eu sou poder',
'Eu sou abundância',
'Eu sou tranquilidade',
' Eu sou saudável',
' Eu sou beleza',
' Eu sou vida',
' Eu sou energia',
' Eu sou positivo', 
' Eu sou determinado',
' Eu sou energia divina',
' Eu sou alegria', 
' Eu sou livre',
' Eu sou vitalidade',
' Eu atraio prosperidade de todo o tipo, porque sou merecedor', 
' As oportunidades surgem por todo o lado, eu sou merecedor e atraio tudo o que é bom',
' Eu sinto uma enorme gratidão por toda abundância que flui para a minha vida',
' Eu estou aberto para que a prosperidade venha a mim com facilidade, alegria e glória',
' Eu atraio todo o tipo de riqueza', 
' Agradeço ao universo por toda a prosperidade e as bênçãos em minha vida',
' Quanto mais agradeço, mais surgem motivos para estar grato',
' Amo cada célula do meu corpo',
' Desejo ter uma velhice saudável e para isso, hoje, cuido com amor do meu corpo',
' Estou sempre a descobrir novas formas de melhorar a minha saúde',
' Mantenho a saúde do meu corpo dando-lhe tudo o que precisa a todos os níveis',
' Meu corpo dedica-se da melhor forma possível a criar uma saúde perfeita',
' Escolho sempre o profissional de saúde certo para as minhas necessidades',
' Agradeço pelo meu corpo saudável, Adoro a vida',
' Os meus pensamentos felizes ajudam a tornar o meu corpo saudável',
' Encher a minha mente de pensamentos prazerosos é o caminho mais rápido para a saúde',
' Dedico uma parte do meu tempo para ajudar os outros, É bom para a minha saúde',
' Respiro profunda e plenamente, Inspiro o sopro da vida o qual me alimenta',
' Faço escolhas saudáveis, Respeito-me',
' Gosto dos alimentos que são os melhores para o meu corpo',
' Faço com amor tudo o que posso para ajudar o meu corpo a manter uma saúde perfeita',
' Uma saúde perfeita é o meu divino direito e eu reivindico-o agora',
' Estou pronto para ser curado, Estou disposto a perdoar, Tudo está bem',
' Mereço as melhores coisas da vida',
' Mereço amor, romance, alegria e tudo de bom que a Vida tem para me oferecer, agora',
' O meu coração está cheio de amor e sei que o amor abre todas as portas',
' Sou uma pessoa bonita e todos me amam, O amor acolhe-me onde quer que eu vá',
' Só atraio relacionamentos saudáveis, Tratam-me sempre bem',
' Agradeço por todo o amor que há na minha vida, Encontro amor em toda parte',
' Escolho olhar o mundo e os outros com olhos de amor, Amo o que vejo',
' O meu coração abre-se para o perdão, Através do perdão, alcanço o amor',
' Hoje presto atenção aos meus sentimentos e cuido de mim amorosamente, Sei que todos os meus sentimentos são meus amigos',
' O passado ficou para trás, não tem nenhum poder agora, Os pensamentos deste momento criam o meu futuro',
' Escolho sentir-me bem comigo mesmo, Mereço o amor que sinto por mim',
' Sou amado e aceito-me exatamente como sou, aqui e agora',
' Sou grata por estar hoje viva, É uma alegria e um prazer viver mais um dia maravilhoso',
' Confio na minha intuição, Presto sempre atenção para ouvir a minha voz interior',
' Hoje terei um ótimo dia',
' Hoje será um dia cheio de realizações positivas', 
' Hoje viverei todas as experiências com felicidade e gratidão',
' Eu mereço tudo de bom que o dia de hoje tem para me oferecer',
' Tenho orgulho de quem eu sou hoje',
' Eu amo o meu corpo como ele é hoje',
' Hoje sentirei a felicidade de viver em positividade',
' Hoje serei grato por tudo que a vida me proporciona', 
' Eu mereço ser feliz hoje',
' Eu escolho ser feliz hoje e todos os outros dias',
' Hoje é um novo dia para realizar novas conquistas e ideais',
' Eu consigo realizar tudo o que planejei durante o dia',
' Tenho o conhecimento para tomar decisões inteligentes para mim hoje',
' Eu quero, eu posso e eu consigo fazer o meu dia ser maravilhoso', 
' Eu faço as escolhas certas o dia todo usando a minha sabedoria interior',
' Hoje eu saio da cama com a certeza que nasci para ser feliz',
' Hoje eu esbanjo amor e alegria onde quer que eu vá',
' Hoje eu quero a leveza da vida',
' Espalho positividade pelo meu caminho de hoje',
];

function sorteio(){
    const escolhida = document.getElementById('frase-escolhida').value;
    const fraserandom = frase[Math.floor(Math.random()* frase.length)]
    
    document.getElementById('resultado').innerHTML=fraserandom
}

